env:
 - CABALVER=1.16 GHCVER=7.0.4
 - CABALVER=1.16 GHCVER=7.2.2
 - CABALVER=1.16 GHCVER=7.4.2
 - CABALVER=1.16 GHCVER=7.6.3
 - CABALVER=1.20 GHCVER=7.8.4
 - CABALVER=1.22 GHCVER=7.10.2
 - CABALVER=head GHCVER=head

matrix:
  allow_failures:
   - env: CABALVER=head GHCVER=head

sudo: false

# It seems that we can't use CABALVER and GHCVER here, so we have to install
# all versions. This looks like a bug on Travis CI.
addons:
  apt:
    sources:
     - hvr-ghc
    packages:
     - ghc-7.0.4
     - ghc-7.2.2
     - ghc-7.4.2
     - ghc-7.6.3
     - ghc-7.8.4
     - ghc-7.10.2
     - ghc-head
     - cabal-1.16
     - cabal-1.20
     - cabal-1.22
     - cabal-head

install:
 - export PATH="/opt/cabal/$CABALVER/bin:/opt/ghc/$GHCVER/bin:$PATH"

before_script:
 - cabal --version
 - cabal update
 - ghc --version
 - ghc-pkg list

script:
 - cabal install --enable-documentation
 - cabal sdist

after_script:
 - ghc-pkg list
