env:
 - CABALVER=1.20 GHCVER=7.0.4
 - CABALVER=1.20 GHCVER=7.2.2
 - CABALVER=1.20 GHCVER=7.4.2
 - CABALVER=1.20 GHCVER=7.6.3
 - CABALVER=1.20 GHCVER=7.8.3
 - CABALVER=head GHCVER=7.8.3
 - CABALVER=head GHCVER=head

matrix:
 allow_failures:
  - env: CABALVER=head GHCVER=head

before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo apt-get update -qq

install:
 - sudo apt-get install -qq cabal-install-$CABALVER ghc-$GHCVER
 - export PATH="/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH"

before_script:
 - cabal --version
 - cabal update
 - ghc --version
 - ghc-pkg list

script:
 - cabal install --enable-documentation
 - cabal sdist -v3

after_script:
 - ghc-pkg list
