env:
 - CABALVER=1.16 GHCVER=7.0.4
 - CABALVER=1.16 GHCVER=7.2.2
 - CABALVER=1.16 GHCVER=7.4.2
 - CABALVER=1.16 GHCVER=7.6.3
 - CABALVER=1.20 GHCVER=7.8.4
 - CABALVER=1.22 GHCVER=7.10.2
 - CABALVER=head GHCVER=head

matrix:
  allow_failures:
   - env: CABALVER=head GHCVER=head

sudo: false

addons:
  apt:
    sources:
     - hvr-ghc
    packages:
     - ghc-$GHCVER
     - cabal-$CABALVER

before_script:
 - cabal --version
 - cabal update
 - ghc --version
 - ghc-pkg list

script:
 - cabal install --enable-documentation
 - cabal sdist

after_script:
 - ghc-pkg list
